### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Loule95450**

### CODE REVIEW

**Comment by Loule95450** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/codingfactory-repos/symfony-orchindeed) found an issue: Complex Method

It's currently on:
[src\Controller\IndexController.php:17-143](https://github.com/CodingFactory-Repos/Symfony-Orchindeed/blob/47b459925c350d0965ab3823e5a897c506186df2/src/Controller/IndexController.php#L17-L143)
Commit 47b459925c350d0965ab3823e5a897c506186df2

**Comment by Loule95450** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/codingfactory-repos/symfony-orchindeed) found an issue: Variable assignment found within a condition. Did you mean to do a comparison ?

It's currently on:
[src\Security\LoginAuthentificatorFormAuthenticator.php:54](https://github.com/CodingFactory-Repos/Symfony-Orchindeed/blob/47b459925c350d0965ab3823e5a897c506186df2/src/Security/LoginAuthentificatorFormAuthenticator.php#L54)
Commit 47b459925c350d0965ab3823e5a897c506186df2

**Comment by Loule95450** [comment]
**_C'est bon pour moi_** 👍

**Review by AyakorK — APPROVED** [review]
LGTM Well done guys !

**Comment by IlanHopti** [comment]
**_Perfect good work team 👍_**

**Pull request merged**
